#!/bin/zsh -e

# TODO: Apply wsl/wsl.conf?
# ln -sfnv "$(realpath wsl/wsl.conf)" "/etc/wsl.conf"

# Packages (consider Nix?)
xargs -a packages/apk sudo apk add # TODO: Restrict to Alpine
adduser $(whoami) docker # Requires new session
# Test these?
# rc-update add docker boot
# rc-service docker start
# source packages/shell-installers # TODO: Test this

source zsh/.zshenv && mkdir -p "${XDG_CONFIG_HOME}"

ln -sfnv "$(realpath zsh)" "${ZDOTDIR}"
ln -sfnv "$(realpath git)" "${XDG_CONFIG_HOME}/git"
ln -sfnv "$(realpath nvim)" "${XDG_CONFIG_HOME}/nvim"
ln -sfnv "$(realpath starship)" "${XDG_CONFIG_HOME}/starship"

zsh
