#!/bin/bash -e

echo -n 'Install packages? (Y/n): '
read response && response="${response:-y}"
if [[ "$response" =~ ^[Yy]$ ]]; then
  source "packages/install-pkgs"
fi

echo -n 'Apply dotfiles? (Y/n): '
read response && response="${response:-y}"
if [[ "$response" =~ ^[Yy]$ ]]; then
  source zsh/.zshenv && mkdir -p "${XDG_CONFIG_HOME}"
  ln -sfnv "$(realpath zsh)" "${ZDOTDIR}"
  ln -sfnv "$(realpath git)" "${XDG_CONFIG_HOME}/git"
  ln -sfnv "$(realpath nvim)" "${XDG_CONFIG_HOME}/nvim"
  ln -sfnv "$(realpath starship)" "${XDG_CONFIG_HOME}/starship"
fi

echo -n 'Update wsl.conf? (Y/n): '
read response && response="${response:-y}"
if [[ "$response" =~ ^[Yy]$ ]]; then
  sudo ln -sfnv "$(realpath wsl/wsl-startup)" '/usr/local/bin/wsl-startup'
  sudo chmod +x '/usr/local/bin/wsl-startup'
  sudo ln -sfnv "$(realpath wsl/wsl.conf)" '/etc/wsl.conf'
  echo 'Restart WSL for the changes to take effect.'
fi

echo -n 'Bind AWS credentials to WSL? (Y/n): '
read response && response="${response:-y}"
if [[ "$response" =~ ^[Yy]$ ]]; then
  WINDOWS_USER=$(cmd.exe /c "echo %USERNAME%" | tr -d '\r')
  CREDENTIALS_PATH="/mnt/c/Users/${WINDOWS_USER}/.aws"
  if [ ! -d "${CREDENTIALS_PATH}" ]; then
    mkdir -v "${CREDENTIALS_PATH}" && \
    touch "${CREDENTIALS_PATH}/config" && \
    touch "${CREDENTIALS_PATH}/credentials"
  fi
  ln -sfnv "${CREDENTIALS_PATH}" ~/.aws
fi

zsh
